package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"fmt"

	"RocketContainer.go/graph/model"
)

// CreateAdvertisement is the resolver for the createAdvertisement field.
func (r *mutationResolver) CreateAdvertisement(ctx context.Context, input model.NewAdvertisement) (*model.Advertisement, error) {
	panic(fmt.Errorf("not implemented: CreateAdvertisement - createAdvertisement"))
}

// CreateAssetReference is the resolver for the createAssetReference field.
func (r *mutationResolver) CreateAssetReference(ctx context.Context, input model.NewAssetReference) (*model.AssetReference, error) {
	panic(fmt.Errorf("not implemented: CreateAssetReference - createAssetReference"))
}

// CreateImage is the resolver for the createImage field.
func (r *mutationResolver) CreateImage(ctx context.Context, input model.NewImage) (*model.Image, error) {
	panic(fmt.Errorf("not implemented: CreateImage - createImage"))
}

// CreateVideo is the resolver for the createVideo field.
func (r *mutationResolver) CreateVideo(ctx context.Context, input model.NewVideo) (*model.Video, error) {
	panic(fmt.Errorf("not implemented: CreateVideo - createVideo"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }
type queryResolver struct{ *Resolver }
*/
