// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Advertisement struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	URL  string `json:"url"`
}

type AssetReference struct {
	AssetID   string    `json:"assetID"`
	AssetType AssetType `json:"assetType"`
}

type Container struct {
	Ads    []*Advertisement `json:"ads"`
	ID     string           `json:"id"`
	Images []*Image         `json:"images"`
	Name   string           `json:"name"`
	Videos []*Video         `json:"videos"`
}

type Image struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	URL  string `json:"url"`
}

type Mutation struct {
}

type NewAdvertisement struct {
	Name string `json:"name"`
	URL  string `json:"url"`
}

type NewAssetReference struct {
	AssetID   string    `json:"assetID"`
	AssetType AssetType `json:"assetType"`
	VideoID   string    `json:"videoID"`
}

type NewImage struct {
	Name string `json:"name"`
	URL  string `json:"url"`
}

type NewVideo struct {
	Description    string    `json:"description"`
	ExpirationDate string    `json:"expirationDate"`
	PlaybackURL    string    `json:"playbackUrl"`
	Title          string    `json:"title"`
	VideoType      VideoType `json:"videoType"`
}

type Query struct {
}

type Video struct {
	Assets         []*AssetReference `json:"assets"`
	Description    string            `json:"description"`
	ExpirationDate string            `json:"expirationDate"`
	ID             string            `json:"id"`
	PlaybackURL    string            `json:"playbackUrl"`
	Title          string            `json:"title"`
	VideoType      VideoType         `json:"videoType"`
}

type AssetType string

const (
	AssetTypeAd    AssetType = "AD"
	AssetTypeImage AssetType = "IMAGE"
)

var AllAssetType = []AssetType{
	AssetTypeAd,
	AssetTypeImage,
}

func (e AssetType) IsValid() bool {
	switch e {
	case AssetTypeAd, AssetTypeImage:
		return true
	}
	return false
}

func (e AssetType) String() string {
	return string(e)
}

func (e *AssetType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AssetType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AssetType", str)
	}
	return nil
}

func (e AssetType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AssetType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AssetType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type VideoType string

const (
	VideoTypeClip    VideoType = "CLIP"
	VideoTypeEpisode VideoType = "EPISODE"
	VideoTypeMovie   VideoType = "MOVIE"
)

var AllVideoType = []VideoType{
	VideoTypeClip,
	VideoTypeEpisode,
	VideoTypeMovie,
}

func (e VideoType) IsValid() bool {
	switch e {
	case VideoTypeClip, VideoTypeEpisode, VideoTypeMovie:
		return true
	}
	return false
}

func (e VideoType) String() string {
	return string(e)
}

func (e *VideoType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = VideoType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid VideoType", str)
	}
	return nil
}

func (e VideoType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *VideoType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e VideoType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
